### ISSUE TITLE
Error decompressing blobs

### ISSUE THREAD

**Issue by mgns** [pmeinhardt/tlr#3]
Seems like it sometimes fails decompressing blobs from the database:

```
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/tailr/app/handlers/api.py", line 22, in wrapper
        return method(self, *args, **kwargs)
      File "/home/tailr/app/handlers/api.py", line 402, in put
        data = decompress(blob.data)
      File "/home/tailr/app/handlers/api.py", line 59, in decompress
        return zlib.decompress(s)
    error: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by pmeinhardt** [comment]
This can happen if the blobs are too long. Unfortunately the database wrapper does not seem to throw an exception when inserting blobs which exceed the maximum length ([currently `2**16 - 1 = 64k - 1` bytes](https://mariadb.com/kb/en/mariadb/blob/)).

I can simply change the `BLOB` column for a [`MEDIUMBLOB`](https://mariadb.com/kb/en/mariadb/mediumblob/) (up to `2**24 - 1 ~ 16m` bytes).
